### ISSUE TITLE
Importing episode data from inpatient episodes

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-research#57]
> We can't search for or pull through patients from the standard elCID used by micro/ID doctors. We were able to do this previously but it doesn't seem to be working now.

**Comment by michaeledwardmarks** [comment]
Didn't we have something similar with OPAT recently?

**Comment by michaeledwardmarks** [comment]
https://github.com/openhealthcare/elcid/issues/670
Not sure if this is related?

**Comment by davidmiller** [comment]
Can't reproduce in test - check on elcidt to see if occurring there.
