### ISSUE TITLE
Add Mycology investigation 

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-research#58]
> We are unable to find anywhere which we can enter details for mycology investigations in any of the fields

This is a request from the RidRTI team - thoughts @GabPoll @michaeledwardmarks  ?

**Comment by GabPoll** [comment]
this is a bit like the virology investigations. The answer is you can already, but the categories are wrong for their purposes. We need a Frank-like spreadsheet of their needs.

**Comment by davidmiller** [comment]
I think the issue here is more that we seem to have had a regression, and a results field is no longer added by default when you freetext the investigation name.

> Test – Mycology
> Date ordered
> Result (as a free text)

**Comment by michaeledwardmarks** [comment]
You get a details box on elcid-0.4 but not both a details and a results box - IIRC I think it has always been like that.

**Comment by davidmiller** [comment]
I thought that you could always enter a 'result' regardless of test type.
(could be wrong).

Does that sound like reasonable behaviour @michaeledwardmarks / @gabpoll

On Mon, 31 Aug 2015 at 04:18 Michael Marks <notifications@github.com> wrote:

> You get a details box on elcid-0.4 but not both a details and a results
> box - IIRC I think it has always been like that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/opal-research/issues/58#issuecomment-136241506>
> .
>
-- 
Best regards

David Miller
Open Health Care

**Comment by michaeledwardmarks** [comment]
Does sound reasonable, not sure if that has ever been the behaviour.

**Comment by davidmiller** [comment]
You're right - it needs to be in micro test other to get results.
